Failed to load schema from http://localhost:9000/swagger/v1/swagger.json
Error: requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /swagger/v1/swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x40248452b0>: Failed to establish a new connection: [Errno 111] Connection refused'))

Add this option to your command line parameters to see full tracebacks: --show-errors-tracebacks
